apiVersion: apps/v1
kind: Deployment
metadata:
  name: restaurant-frontend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      labels:
        app: frontend
    spec:
      containers:
        - name: frontend
          image: ducky92fr/frontend:latest
          ports:
            - containerPort: 80
          env:
            - name: "REACT_APP_AUTH_SERVICE_URL"
              value: "haproxy-service.default"
