apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig

metadata:
  name: restaurant-app-cluster
  region: eu-west-3

nodeGroups:
  - name: ng-1
    instanceType: t3.small
    desiredCapacity: 2
    minSize: 1
    maxSize: 3
    volumeSize: 20
    ssh:
      allow: true
