---
- name: Deploy Docker containers
  hosts: all
  become: true
  vars:
    dockerhub_username: "{{ dockerhub_username }}"
    dockerhub_token: "{{ dockerhub_token }}"

  tasks:
    - name: Run auth service container
      docker_container:
        name: backend-auth-service
        image: "{{ dockerhub_username }}/backend-auth-service:latest"
        state: started
        restart_policy: always
        ports:
          - "80:3001"
      when: inventory_hostname == 'my-backend-auth'

    - name: Run discounts service container
      docker_container:
        name: backend-discounts-service
        image: "{{ dockerhub_username }}/backend-discounts-service:latest"
        state: started
        restart_policy: always
        ports:
          - "80:3002"
      when: inventory_hostname == 'my-backend-discount'

    - name: Run items service container
      docker_container:
        name: backend-items-service
        image: "{{ dockerhub_username }}/backend-items-service:latest"
        state: started
        restart_policy: always
        ports:
          - "80:3003"
      when: inventory_hostname == 'my-backend-items'

    - name: Run HAProxy container
      docker_container:
        name: haproxy
        image: "{{ dockerhub_username }}/haproxy:latest"
        state: started
        restart_policy: always
        ports:
          - "80:80"
        env:
          HAPROXY_SERVICE_URL: "http://{{ haproxy_ip }}"
      when: inventory_hostname == 'my-haproxy'

    - name: Run frontend container
      docker_container:
        name: frontend
        image: "{{ dockerhub_username }}/frontend:latest"
        state: started
        restart_policy: always
        ports:
          - "80:80"
      when: inventory_hostname == 'my-frontend'
